### ISSUE TITLE
selectors with `py` not converted properly?

### ISSUE THREAD

**Issue by beckermr** [conda-incubator/conda-recipe-manager#198]
**What happened?**

When converting a feedstock here: https://github.com/conda-forge/conda-smithy/issues/2085#issuecomment-2407734898

we saw that a selector with `py` in it (`[py<310]`) was converted to a list element as `py<310`. However, in the new v1 format for python, the correct syntax is `match(python, '<3.10')` AFAIK. We have no formal spec but I don't think there is an intent to support the `py` variable going forward.

**To Reproduce**

**Additional Details (please complete the following information):**
 - OS: [e.g. MacOS M1, Windows]
 - Conda Recipe Manager version [e.g. `0.2.0`]
 - Any other context about the problem that was found.

**Comment by schuylermartin45** [comment]
@beckermr I think this might have been resolved in `v0.3.0` (released today) with this PR: https://github.com/conda-incubator/conda-recipe-manager/commit/1fd4f9d1d49b38ff4b321cdca6c67bb11f74496b#diff-b9a300b1f9ce0acd937e2905a1f0af470afae7049450ef4158b16ae31254cda4R209

I assume most conda-forge contributors are getting CRM from conda-forge and not the source code. That's on me for not releasing more frequently.

**Comment by schuylermartin45** [comment]
Confirmed, `v0.3.0` does not suffer from this issue. I ran `crm convert` on this recipe: https://github.com/conda-forge/sourmash-minimal-feedstock/blob/main/recipe/meta.yaml

Here's the afflicted build section output:
```
build:
  number: 2
  skip: match(python, "<3.10")
  python:
    entry_points:
      - sourmash = sourmash.__main__:main
  dynamic_linking:
    missing_dso_allowlist:
      - if: osx
        then: /usr/lib/libresolv.9.dylib
```
