### ISSUE TITLE
Parser is not resilient to mixed indentation

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/conda-recipe-manager#221]
The irony is not lost on me given we work in `Python` around here.

The CRM parser will crash if some sections use the wrong indentation. Note that the fields in the `build` section use 4 spaces (not 2) in the following example:
```yaml
source:
  url: https://pypi.io/packages/source/o/olefile/olefile-{{ version }}.zip
  sha256: 133b031eaf8fd2c9399b78b8bc5b8fcbe4c31e85295749bb17a87cba8f3c3964

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
```

The parser assumes 2 spaces for indentation as the vast, vast, majority of recipe files conform to this "standard". This will likely not be easy to fix.
