### ISSUE TITLE
Un-indented comments crash parser

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/conda-recipe-manager#222]
Comments that do not match the same level of indentation as the section they exist in will crash the parser.

Example:
```yaml
test:
  imports:
    - can
    - can.interfaces
#    - can.interfaces.etas
#    - can.interfaces.ics_neovi
#    - can.interfaces.ixxat
#    - can.interfaces.kvaser
#    - can.interfaces.neousys
#    - can.interfaces.pcan
#    - can.interfaces.seeedstudio
    - can.interfaces.serial
    - can.interfaces.socketcan
    - can.interfaces.socketcand
```
(from https://github.com/AnacondaRecipes/python-can-feedstock/blob/main/recipe/meta.yaml)
