### ISSUE TITLE
Conversion adds `pip-check: false` on non-python packages

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/conda-recipe-manager#23]
This comes out of a logical misinterpretation of the CEP-14:
https://github.com/conda-incubator/ceps/blob/main/cep-14.md#python-test-element

`pip_check` defaults to `true` IFF the package is a Python package. For non-Python packages, this is an error.

TODO: We need a way to classify recipes as building "python" packages that is reliable and consistent.

**Comment by schuylermartin45** [comment]
After some experimentation with this fake recipe file, running ``

```yaml
package:
  name: test
  version: 1.0.0

requirements:
  host:
    - python
    - requests
  run:
    - python
    - requests
```

We get:
- As written, this produces: `conda-bld/osx-arm64/test-1.0.0-py311_0.tar.bz2`
- `host/python` redacted: `conda-bld/osx-arm64/test-1.0.0-py312_0.tar.bz2`
- `run/python` redacted: `conda-bld/osx-arm64/test-1.0.0-0.tar.bz2`
- Both redacted: `conda-bld/osx-arm64/test-1.0.0-0.tar.bz2`
