### ISSUE TITLE
Selectors in a list are not being converted properly

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/conda-recipe-manager#25]
From the conda-build element chat:

```yaml
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
```
is not quite corretly translated (only the first of the two elements makes it into the `then` part of the condition.

**Comment by schuylermartin45** [comment]
Confirmed, here are the results with a very basic recipe file:
Input:
```yaml
build:
  - python                                 # [build_platform != target_platform]
  - cross-python_{{ target_platform }}     # [build_platform != target_platform]
```

Output:
```yaml
schema_version: 1

context:

build:
  - if: build_platform != target_platform
    then: python
  - cross-python_${{ target_platform }}
```
