### ISSUE TITLE
cannot parse recipe with jinja `{% if` branches

### ISSUE THREAD

**Issue by minrk** [conda-incubator/conda-recipe-manager#258]
**What happened?**

cannot parse recipe with jinja conditional branches, meaning it cannot be used for `conda-smithy recipe-lint` on conda-forge.

**To Reproduce**

Sample recipe:

```yaml
{% set variable = 10 %}
package:
  name: test-pkg
  version: 1.0.0

source:
  url: https://doesntmatter.horse

build:
  number: 1

requirements:
  host:
    {% if variable >= 10 %}
    - libblas
    {% endif %}

extra:
  recipe-maintainers:
    - minrk
```

- OS: mac m1
- Conda Recipe Manager version 0.3.4

```python
from conda_recipe_manager.parser.recipe_parser import RecipeParser

with open("recipe/meta.yaml") as f:
    RecipeParser(f.read())
```

gives:

```
File ~/conda/lib/python3.11/site-packages/conda_recipe_manager/parser/recipe_reader.py:480, in RecipeReader.__init__(self, content)
    478     depth_to_pop = (cur_indent - new_indent) // TAB_SPACE_COUNT
    479     for _ in range(depth_to_pop):
--> 480         node_stack.pop()
    481 cur_indent = new_indent
    482 # Look at the stack to determine the parent Node and then append the current node to the new parent.

IndexError: pop from empty list
```
