### ISSUE TITLE
fails to parse summary with colon

### ISSUE THREAD

**Issue by minrk** [conda-incubator/conda-recipe-manager#284]
**What happened?**

When there is a colon in `about.summary`, quotation marks are stripped during recursive parsing, leading to parse errors like:

```
EXCEPTION: An exception occurred while parsing the recipe file
mapping values are not allowed in this context
  in "<unicode string>", line 1, column 17
0 errors and 0 warnings were found.
```

without any context (the actual line is 26), even with `--debug`.

**To Reproduce**

Create `meta.yaml`:

```
{% set version = "1.0" %}
{% set build = 1 %}

package:
  name: test
  version: {{ version }}

source:
  url: https://example.org/{{ version }}.tar.gz
  sha256: 83624de0178b42d37ca1f7f905e1093556c6919fe5accd3e9f11d00a66e11256

build:
  number: {{ build }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
test:
  commands:
    - "true"

about:
  home: https://example.com
  summary: "project: description"

extra:
  recipe-maintainers:
    - minrk
```

Run:

```
crm convert --debug meta.yaml
```

get

```
EXCEPTION: An exception occurred while parsing the recipe file
mapping values are not allowed in this context
  in "<unicode string>", line 1, column 17
0 errors and 0 warnings were found.
```

(notably, there is no debug info in the output).

Digging in with a debugger, the problem appears to be caused by stripping quotes on the `summary` line, because the line:

```yaml
summary: project: description
```

is passed to yaml to parse, instead of the actual line `summary: "project: description"`

**Additional Details (please complete the following information):**
 - OS: macOS 15.2, arm
 - Conda Recipe Manager version `0.4.0`

An easy enough workaround is to switch to

```yaml
summary: |
    project: description
```

which parses fine
