### ISSUE TITLE
Add full support for evaluating V0 JINJA ternary variables

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/conda-recipe-manager#285]
As discovered while working on #276, CRM currently cannot render/interpret JINJA ternary variables like:

```yaml
{% set posix = 'm2-' if win else '' %}
```

The stop-gap solution in #276 will be to leave the statement as $-escaped JINJA when the variable is substituted:
```yaml
requirements:
  build:
    - {{ posix }}foo
```
becomes
```yaml
requirements:
  build:
    - ${{ 'm2-' if win else '' }}foo
```

I don't think it would be wise to spend time on this endeavor, but I will create this ticket to track it. I'm not sure how important this will be in the V1 format.
