### ISSUE TITLE
`convert` command produces invalid `tests` section

### ISSUE THREAD

**Issue by martin-g** [conda-incubator/conda-recipe-manager#289]
**What happened?**

`conda-recipe-manager convert ./su2/meta.yaml > ./su2/recipe.yaml` produced an issue:

meta.yaml: 
```
{% set name = "su2" %}
{% set version = "8.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/su2code/SU2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d550be60ccc8cb907d53a0531715b229585f1e92e2e8e22ab2e8a181d096e7c9
  patches:
    - su2-meson.patch

build:
  skip: True  # [win or osx]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - make
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - ccache
    - swig
  host:
    - python
    - mpi4py
    - openblas
    - openmpi
    - zlib
  run:
    - python
    - libopenblas
    - openmpi

test:
  commands:
    - SU2_CFD --help
    # The following items have no `--help` and require config file to be run
    - test -x ${PREFIX}/bin/SU2_DEF
    - test -x ${PREFIX}/bin/SU2_DOT
    - test -x ${PREFIX}/bin/SU2_GEO
    - test -x ${PREFIX}/bin/SU2_SOL

about:
  home: https://su2code.github.io
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: An Open-Source Suite for Multiphysics Simulation and Design
  doc_url: https://su2code.github.io/docs_v7/home/
  dev_url: https://github.com/su2code/SU2

extra:
  recipe-maintainers:
    - martin-g
 ```

produced recipe.yaml: 
```
schema_version: 1

context:
  name: su2
  version: 8.1.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/su2code/SU2/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d550be60ccc8cb907d53a0531715b229585f1e92e2e8e22ab2e8a181d096e7c9
  patches:
    - su2-meson.patch

build:
  number: 0
  skip: win or osx

requirements:
  build:
    - make
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - pkg-config
    - ccache
    - swig
  host:
    - python
    - mpi4py
    - openblas
    - openmpi
    - zlib
  run:
    - python
    - libopenblas
    - openmpi
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x') }}

tests:
  - python:
      pip_check: false
  - script:
      - SU2_CFD --help
      - test -x ${PREFIX}/bin/SU2_DEF
      - test -x ${PREFIX}/bin/SU2_DOT
      - test -x ${PREFIX}/bin/SU2_GEO
      - test -x ${PREFIX}/bin/SU2_SOL

about:
  license: GPL-2.0-or-later
  license_file: LICENSE.md
  summary: An Open-Source Suite for Multiphysics Simulation and Design
  homepage: https://su2code.github.io
  repository: https://github.com/su2code/SU2
  documentation: https://su2code.github.io/docs_v7/home/

extra:
  recipe-maintainers:
    - martin-g
```

the [logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1149913&view=logs&j=4cabe686-70ae-553a-7fd0-310379f2cbac&t=6a4fc7c9-c31a-5115-eff9-6479d72b69ff&l=661) print this error:
```
Error:
  × Failed to parse recipe

Error:
  × Parsing: missing field `imports`
    ╭─[45:16]
 44 │   - python:
 45 │       pip_check: false
    ·                ───┬───
    ·                   ╰── here
 46 │   - script:
    ╰────
  help: expected field `imports` in python test to be a list of imports
```

That is,
```
tests:
  - python:
      pip_check: false
```
is totally new and breaks the test execution.

**To Reproduce**

Use the [meta.yaml](https://github.com/conda-forge/staged-recipes/pull/28726/files#diff-df35e76c621c4a8e49cb1b5036620c279968fa10e9d573852187f567bafe7a51) from https://github.com/conda-forge/staged-recipes/pull/28726

**Additional Details (please complete the following information):**
 - OS: Ubuntu 24.04
 - Conda Recipe Manager version [e.g. `0.2.0`]: 0.4.0
 - Any other context about the problem that was found.
