### ISSUE TITLE
Invalid and empty script test section in V1 recipe

### ISSUE THREAD

**Issue by hadim** [conda-incubator/conda-recipe-manager#310]
Consider the following `meta.yaml` file at https://github.com/conda-forge/adaptive-scheduler-feedstock/blob/d0427642fecded9db726907d34fcf210de03e902/recipe/meta.yaml

After conversion with `conda-recipe-manager`, the test section is invalid:

```yaml
# ...

tests:
  - python:
      imports:
        - adaptive_scheduler
      pip_check: false
  - requirements:
      run:
        - python ${{ python_min }}

# ...
```

The section

```yaml
  - requirements:
      run:
        - python ${{ python_min }}
```

should be removed since it does not contain a `script` section and so is invalid.

I think the fix should be as simple as removing any script section when the key `script` is missing.

Waiting for a fix here, I added a simple patch to `feedrattler`: https://github.com/hadim/feedrattler/blob/c001b6e01da868a4497e964767f5ba0194d51827/src/feedrattler/utils.py#L172-L205

_Originally reported at https://github.com/hadim/feedrattler/issues/7_
