### ISSUE TITLE
Single item script issue converting to rattler build

### ISSUE THREAD

**Issue by henryiii** [conda-incubator/conda-recipe-manager#316]
**What happened?**

If `script:` is not a list, rattler-build crashes. It should be converted into a one-item list.

**To Reproduce**

`pixi exec feedrattler scikit-build-feedstock henryiii`

**Comment by schuylermartin45** [comment]
According to [the CEP](https://github.com/conda/ceps/blob/main/cep-0014.md#build-section) a `string` is completely valid in this field. I think this might be a bug or missing feature of `rattler-build` and we should file a ticket there accordingly.

**Comment by henryiii** [comment]
Ahh, I was confused by the error message. Running it in two explicit steps and adjusting the output file by hand shows that `tests: commands:` is being thrown away, and it seems `script` is required. According to the CEP, there is no `tests: commands:` in v1.


```
Error:   × Failed to parse recipe

Error:
  × missing field `script`
    ╭─[../../../../../private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/tmpqm3bz5di/scikit-build-feedstock/recipe/recipe.yaml:42:10]
 41 │           python_version: ${{ python_min }}.*
 42 │ ╭─▶   - files:
 43 │ │         source:
 44 │ │           - tests/*
 45 │ │           - pyproject.toml
 46 │ │
 47 │ ├─▶ about:
    · ╰──── here
 48 │       license: MIT
    ╰────
  help: expected field `script` to be a list of commands
...
CalledProcessError: Command '['rattler-build', 'build', '--render-only', '--recipe', '/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/tmpqm3bz5di/scikit-build-feedstock/recipe', '--target-platform', 'linux-64', '--build-platform', 'linux-64', '-m',
'/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/tmp13jajjjm']' returned non-zero exit status 1.
```

The input looked like this:

```yaml
test:
  imports:
    - skbuild
  source_files:
    - tests/*
    - pyproject.toml
  commands:
    - pip check
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - cython
    - git
    - make
    - path.py
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - requests
    - setuptools
    - virtualenv
    - wheel
```

And the output looks like this:

```yaml
tests:
  - python:
      imports:
        - skbuild
      pip_check: true
  - files:
      source:
        - tests/*
        - pyproject.toml
```

Which is incorrect, the correct output is something like this, I think:

```yaml
tests:
  - python:
      imports:
        - skbuild
      pip_check: true
  - script:
      - pip check
  - script:
      file: run_test
    files:
      source:
        - tests/*
        - pyproject.toml
```
