### ISSUE TITLE
convert: `ignore_run_exports_from` not converted correctly

### ISSUE THREAD

**Issue by lucascolley** [conda-incubator/conda-recipe-manager#325]
**What happened?**
I'm trying to convert a recipe which contains the following section: https://github.com/lucascolley/starship-feedstock/blob/3f03cf78793fe386a12d1acbbc45d0e595c4104c/recipe/meta.yaml#L14-L17

Invalid V1 syntax is produced:

```yaml
build:
  number: 1
  ignore_run_exports_from:
    # we want to ignore libstdcxx, but not libgcc; the latter also comes in through
    # compiler('c'), and conda keeps that despite ignoring the cxx run-exports
    - ${{ compiler('cxx') }}
```

It looks like we want something like

```yaml
  requirements:
    ignore_run_exports:
      from_package:
        - ${{ compiler('cxx') }}
```

reading https://rattler.build/latest/reference/recipe_file/#ignore-run-exports.

**To Reproduce**

Steps to reproduce the behaviour: 

```
❯ pixi exec --list=recipe feedrattler starship-feedstock --log-level=ERROR
The environment has 1 packages filtered by regex `recipe`:
Package               Version  Build         Size
conda-recipe-manager  0.4.2    pyhd8ed1ab_0  213.5 KiB
Package               Version  Build         Size


 ╭─ Finding outputs from recipe
 │ Loading variant config file: "/var/folders/_j/kscn3hgd6x995v65h1b3gnrm0000gn/T/tmpytg1fuos"
 │
 ╰─────────────────── (took 0 seconds)
Error:   × Failed to parse recipe

Error: 
  × invalid field `ignore_run_exports_from`.
    ╭─[../../../../private/var/folders/_j/kscn3hgd6x995v65h1b3gnrm0000gn/T/tmp9gmg7x7a/starship-feedstock/recipe/recipe.yaml:17:3]
 16 │   number: 1
 17 │   ignore_run_exports_from:
    ·   ───────────┬───────────
    ·              ╰── here
 18 │     # we want to ignore libstdcxx, but not libgcc; the latter also comes in through
    ╰────
  help: valid options for build are number, string, skip, script, noarch, python, dynamic_linking,
        always_copy_files, always_include_files, merge_build_and_host_envs, variant,
        prefix_detection, post_process, files

```

**Additional Details (please complete the following information):**
 - OS: MacOS
 - Conda Recipe Manager version 0.4.2
