### ISSUE TITLE
Improve V0 --> V1 conversion support for `join` and `split` operations in JINJA

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/conda-recipe-manager#327]
See the TODO introduced in #326 for more context:

```py
    JINJA_FUNCTIONS_SET: Final[set[re.Pattern[str]]] = {
        JINJA_FUNCTION_LOWER,
        JINJA_FUNCTION_UPPER,
        JINJA_FUNCTION_REPLACE,
        # TODO FIX: Adding `split` and `join` to this list causes some odd bracket-escaping in the
        # `regression_jinja_sub.yaml` upgrade test. This will require additional investigation, but for now, IMO the
        # old behavior is a little less wrong, so we'll leave it as is.
        # JINJA_FUNCTION_SPLIT,
        # JINJA_FUNCTION_JOIN,
        JINJA_FUNCTION_IDX_ACCESS,
        JINJA_FUNCTION_ADD_CONCAT,
        JINJA_FUNCTION_MATCH,
    }
```

When the `split` and `join` regular expressions are added to this set, it causes one of the V0 --> V1 regression tests to trip. The expected:
```yaml
context:
  name: types-toml
  version: 0.10.8.6
  soversion: "\"\".\".join(version.split(\".\")[:3])\""
```
in `v1_regression_jinja_sub.yaml` now transforms into
```yaml
context:
  name: types-toml
  version: 0.10.8.6
  soversion: "{{\"\".\".join(version.split(\".\")[:3])\}}""
```

This must be some quark of mixing the already problematic quoting string function with the `{{`/`}}` escaping logic in the upgrade path code.

Further investigation is warranted.
