### ISSUE TITLE
What to do with `/build/rpaths`

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/conda-recipe-manager#46]
`r-highr-feedstock` contains a list of strings under `/build/rpaths`:

```yaml
build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/
```

This does not appear in CEP-13 nor CEP-14 and `rattler-build` does not currently support this path. There is a new `/build/dynamic_linking/rpaths` but that is a different transformation which we recently added support for.

`rattler-build` error:
```
Error:   × Parsing: invalid field `rpaths`.
    ╭─[51:3]
 50 │   merge_build_host: $${{ true if win }}
 51 │   rpaths:
    ·   ───┬──
    ·      ╰── here
 52 │     - lib/R/lib/
    ╰────
```
